import { mkdtemp, readFile, readdir, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import process from "node:process";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";

const execFileAsync = promisify(execFile);

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");
const generatedHermesRoot = path.join(repoRoot, "generated", "hermes");
const readmePath = path.join(repoRoot, "README.md");
const grimoirePath = path.join(repoRoot, "GRIMOIRE.md");
const blueprintPath = path.join(repoRoot, "catalog", "blueprints.json");
const packagePath = path.join(repoRoot, "package.json");

function assert(condition, message) {
  if (!condition) {
    throw new Error(message);
  }
}

async function readJson(targetPath) {
  return JSON.parse(await readFile(targetPath, "utf8"));
}

async function collectHermesSkills(rootDir) {
  const categories = [];
  const skillFiles = [];

  for (const entry of await readdir(rootDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) {
      continue;
    }

    const categoryDir = path.join(rootDir, entry.name);
    const categoryEntries = await readdir(categoryDir, { withFileTypes: true });
    const skillDirs = categoryEntries.filter((child) => child.isDirectory());
    categories.push({ slug: entry.name, skillCount: skillDirs.length, hasDescription: categoryEntries.some((child) => child.isFile() && child.name === "DESCRIPTION.md") });

    for (const skillDir of skillDirs) {
      skillFiles.push(path.join(categoryDir, skillDir.name, "SKILL.md"));
    }
  }

  return { categories, skillFiles };
}

function requireAll(content, requiredSnippets, label) {
  for (const snippet of requiredSnippets) {
    assert(content.includes(snippet), `${label} is missing required content: ${snippet}`);
  }
}

async function validateDocs(packageJson) {
  const readme = await readFile(readmePath, "utf8");
  const grimoire = await readFile(grimoirePath, "utf8");

  requireAll(readme, [
    "<!-- Generated by scripts/render-skills.mjs.",
    "## Quick Install",
    "## Verification",
    "npm run verify",
    "procedural markdown with YAML frontmatter, not executable plugins by themselves",
    "## Field-Tested Favorites"
  ], "README.md");

  requireAll(grimoire, [
    "<!-- Generated by scripts/render-skills.mjs.",
    "# Grimoire",
    "## At a Glance",
    "## Browse by Category"
  ], "GRIMOIRE.md");

  assert(typeof packageJson.version === "string" && packageJson.version.length > 0, "package.json must declare a version");
}

async function validateGeneratedSurfaces(packageJson, blueprints) {
  const expectedHermesCount = blueprints.entries.filter((entry) => entry.provider_targets.includes("hermes")).length;

  const { categories, skillFiles: hermesSkillFiles } = await collectHermesSkills(generatedHermesRoot);

  assert(categories.length > 0, "generated/hermes must contain at least one category");
  assert(hermesSkillFiles.length === expectedHermesCount, `generated/hermes count mismatch: expected ${expectedHermesCount}, found ${hermesSkillFiles.length}`);

  for (const category of categories) {
    assert(category.hasDescription, `Hermes category ${category.slug} is missing DESCRIPTION.md`);
    assert(category.skillCount > 0, `Hermes category ${category.slug} has no skills`);
  }

  for (const skillPath of hermesSkillFiles) {
    const content = await readFile(skillPath, "utf8");
    requireAll(content, [
      "---\nname:",
      `version: \"${packageJson.version}\"`,
      "compatibility: \"Hermes Agent skills system\"",
      "metadata:\n  hermes:\n    tags:",
      "## What This Skill Does",
      "## Procedure",
      "## Deliverables",
      "## Pitfalls / Guardrails",
      "## Verification",
      "## Example Invocation"
    ], skillPath);
  }

  return {
    hermesCategoryCount: categories.length,
    hermesSkillCount: hermesSkillFiles.length
  };
}

async function runInstallCheck(tempRoot) {
  const hermesHome = path.join(tempRoot, "hermes-home");
  const nodeBinary = process.execPath;

  await execFileAsync(nodeBinary, [path.join(repoRoot, "scripts", "install-hermes-skills.mjs")], {
    cwd: repoRoot,
    env: { ...process.env, HERMES_HOME: hermesHome }
  });

  const hermesSkillsRoot = path.join(hermesHome, "skills");
  const hermesEntries = await readdir(hermesSkillsRoot, { withFileTypes: true });

  assert(hermesEntries.some((entry) => entry.isFile() && entry.name === ".wizardsoftheghosts-manifest.json"), "Hermes sandbox install did not write a manifest");
  assert(hermesEntries.some((entry) => entry.isDirectory()), "Hermes sandbox install did not create any category directories");
}

const packageJson = await readJson(packagePath);
const blueprints = await readJson(blueprintPath);

await validateDocs(packageJson);
const surfaceStats = await validateGeneratedSurfaces(packageJson, blueprints);

const tempRoot = await mkdtemp(path.join(os.tmpdir(), "wizardsoftheghosts-verify-"));

try {
  await runInstallCheck(tempRoot);
} finally {
  await rm(tempRoot, { recursive: true, force: true });
}

console.log(`Verified README and GRIMOIRE generation markers.`);
console.log(`Verified ${surfaceStats.hermesSkillCount} Hermes skills across ${surfaceStats.hermesCategoryCount} categories.`);
console.log("Verified sandbox installs for Hermes and Codex homes.");